SOLAR_SLUG = '/solar'
GLOBAL_WARMING_SLUG = '/global-warming'
TICKER_SLUG = '/ticker'
USER_SLUG='/user'
LIFE_EXPECTANCY_SLUG='/life'
TABLE_EXAMPLE_SLUG = '/table'
TERMS_AND_CONDITIONS_SLUG='/terms'
TRANSACTIONS_SLUG = "/pages/transactions"

NAVBAR_PAGES = (TABLE_EXAMPLE_SLUG, TRANSACTIONS_SLUG, SOLAR_SLUG, GLOBAL_WARMING_SLUG, TICKER_SLUG, LIFE_EXPECTANCY_SLUG)
